### ISSUE TITLE
Ideen für Forschungsfragen

### ISSUE THREAD

**Issue by jposselt** [jposselt/PVModulfehler#8]

**Comment by tnentwig** [comment]
Korrelieren Wetterdaten mit Leistungsdaten?

**Comment by mariuswarning** [comment]
Wie können natürliche Ereignisse (Verschmutzung, Schnee, sporadische Bewölkung) von Fehlern unterschieden werden?

**Comment by Niklas3006** [comment]
# Bedeutung der csv-Daten im Detail 
* Schein-/Wirkleistung
* Modulanzahl in String
* etc.
