### ISSUE TITLE
Prototyp für Datenzusammenführung aus DarkSky und Leistungsdaten aus CSV-Beispieldatei

### ISSUE THREAD

**Issue by tnentwig** [jposselt/PVModulfehler#9]
Protoypischer Versuch der Darstellung des Leistungsverlaufs in Abhängigkeit des Wetters
Bewölkt --> niedrige Leistung, Sonnig --> Hohe Leistung
Leistungsschwankungen durch Wetterschwankungen

**Comment by tnentwig** [comment]
DarkSky Api kann nicht mehr verwendet werden. Alternativen suchen? #10

**Comment by jposselt** [comment]
Erster Prototyp für das Mergen von Wetter- und PV-Daten ist im Repo
